### ISSUE TITLE
Can't Override Ctrl-Shift-S (Debugger)

### ISSUE THREAD

**Issue by sudleyplace** [trlkly/dorando-keyconfig#10]
This key combination is listed in Keyconfig's dialog as a line to manage and it allows me to disable it or change its keystroke to something else.  However, after a reboot, the Keyconfig dialog shows the old key combination in place, and indeed, pressing that key combo invokes the Debugger.

Am I not saving my changes properly?  I thought that just closing the dialog would save the changes. as there are no Save or Discard buttons.

How can I override this key combination as I'm using AutoHotKey for a different behavior which I'd like to be universal.

If this key combo is not overrideable, then you might want to either remove it or mark it as such.

**Comment by trlkly** [comment]
The setting is saving, but something in Firefox is apparently changing it back upon restart. Still, the setting is still there. It may be possible to make a workaround that would reactivate the key every time Firefox starts, but I'm not sure when I'll be able to work on that. 

However, for your use case, you should be able to do what you want just using your AutoHotkey script. Just assign Ctrl-Shift-S to another key combination when Firefox is the active window, like so:

    #IfWinActive, ahk_class MozillaWindowClass 
       ^!s::send ^+s  ;makes Ctrl-Alt-S = Ctrl-Shift-S
    #IfWinActive

Then change your hotkey from ``^+s::`` to ``$^+s::``  so that it can't be triggered by other hotkeys. And, of course, you can change ^!s to whatever hotkey you want--that was just my example.

**Comment by trlkly** [comment]
And now I'm closing this as it's the same bug as #4
