### ISSUE TITLE
window.scrollTo(x,y) and window.scrollBy(x,y) not working

### ISSUE THREAD

**Issue by fschrofner** [trlkly/dorando-keyconfig#3]
I'm trying to set a key combination to scroll to top and bottom, as well as down and up by a certain value. I couldn't find the default keybindings (pos1, end, pgup, pgdown) to overwrite them, so I tried doing the same by using JavaScript.

Setting the key combination Alt+< to `window.alert("test");` works fine, but setting it to `window.scrollTo(0,0);` does nothing.  

Am I doing something wrong here? Do I have to take a different approach? Is it a bug?

**Comment by fschrofner** [comment]
Oh I forgot to mention, that I'm using Pale Moon. Could it be a compatibility issue?

**Comment by trlkly** [comment]
I'm really not the best person to ask about how to make a script work. There's a link [to the forum topic](http://forums.mozillazine.org/viewtopic.php?t=72994) in that link where I tell you where to go to learn more. Maybe I should have a direct link to the forum in there, too. 

Anyways, the problem is probably that keyconfig isn't executing JavaScript on the webpage, but on the browser window itself. So you don't have direct access to window.scrollTo.

Taking a brief look at the forums, it seems the commands you want are
`goDoCommand('cmd_scrollTop'); //scroll to top
    goDoCommand('cmd_scrollBottom'); //scroll to bottom
    goDoCommand('cmd_scrollLineDown'); // scroll down a short distance
    goDoCommand('cmd_scrollPageDown'); // PgDn -- I guessed
    goDoCommand('cmd_scrollLineUp');  // scroll up a short amount
    goDoCommand('cmd_scrollPageUp');// PgUp -- I guessed`

Please close this bug if these work for you.

**Comment by fschrofner** [comment]
You're correct, it works that way! I must have done something wrong, because I tried the goDo commands as wel beforel..  
Anyhow: thanks for your help and for keeping this amazing addon alive!
